### ISSUE TITLE
Unable to launch application(Gtk-WARNING **: cannot open display: :0)

### ISSUE THREAD

**Issue by laichiaheng** [Lin-Buo-Ren/audio-recorder-snap#4] opened 2018-10-24 13:19 UTC
Error:Invalid command line argument. Cannot open display: 

(audio-recorder:7958): Gtk-WARNING **: cannot open display: :0

OS: Ubuntu 18.04

**Comment by brlin-tw** [comment] 2019-03-09 09:48
Hello, apologies for long time ignorance.  Can you still reproduce this issue?
Also are you using a Wayland session?

**Comment by laichiaheng** [comment] 2019-03-09 12:58
@Lin-Buo-Ren 沒辦法，我換到 Manjaro 後不曉得如何使用 snap 了
我是在 Xorg 下使用的

**Comment by brlin-tw** [comment] 2019-03-09 14:45
You can install snapd in Manjaro Linux by following the documentation: [Installing snap on Manjaro Linux - Documentation for snaps: Universal Linux packages](https://docs.snapcraft.io/installing-snap-on-manjaro-linux/6807)

But as it's an Arch you probably don't need it in the first place ;)

Anyway as the issue is not reproducible at my end I'll close this issue, for now, feel free to visit it if you ever encounter it again.  Thanks for your effort in reporting this issue!

**Closed as completed by brlin-tw** 2019-03-09 14:45 UTC
